### ISSUE TITLE
Short hash

### ISSUE THREAD

**Issue by lclpsoz** [UnlimitedHugs/RimworldRemoteExplosives#1]
Every time I start rimworld I receive this error message:

```
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

FlameBomb already has short hash.

(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

SleepingGas already has short hash.

(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

PlantSparkweed already has short hash.
```

[output_log.txt](https://github.com/UnlimitedHugs/RimworldRemoteExplosives/files/557265/output_log.txt)

**Comment by UnlimitedHugs** [comment]
You must be playing on the early release of A15c. I'd recommend you update to build 1284 where this bug is fixed.

**Comment by UnlimitedHugs** [comment]
By the way, this error is harmless- you don't have to update, you can simply ignore it.
