### ISSUE TITLE
Suggestions:

### ISSUE THREAD

**Issue by Tylertron1998** [UnlimitedHugs/RimworldRemoteExplosives#6]
Hey! I love your mod.

I do have a few suggestions though:

1: More channels. I currently have a base half in the mountains; with a big opening to err... encourage raiders to go through that way. They walk through, then BLAM.

SEALING FOAM.

~~DEADLY NEUROTOXINS~~ SLEEPING GAS.

However.. I have 3 channels already taken up. So; the first is for the sealing foam, the second is for the sleeping gas, and the third is a "backup" sealing foam, just incase. Now - if I wanted to say, have some explosives scattered about on a different channel, I don't have a choice. 8 channels I think would do.

2: Add a remote channel upgrade to the gas vent; currently there is an easy work around (just use a power switch) but it's not the most.. finesse way of doing it.

3: Range extenders for remote explosives - imagine:

Everything has gone to hell. Your crops, blighted. All but one pawn are dying in there bed... you're running super low on food.. and then, BOOM.

Incoming raid. You have no choice... explode EVERY explosive on the map. All out hell.

- suggestion for this: make it powered, and have it breakdown every so often. Would make for good balancing.

4: An "advanced" mountain roof removal explosive. The mountain roof removal is AWESOME. I hate mountains. However, it's range kinda... sucks. This is why I suggest and "advanced" one - with better range. I wouldn't mind paying 4x the cost in materials for this... to be honest.

Love your mod! Thank you for the extra explosive fun!

**Comment by Tylertron1998** [comment]
Oh also - side suggestion: A small 1x1 thing??? Not sure what you'd call it. But to detonate explosives when power is recieved - purely for use with this mod:
https://ludeon.com/forums/index.php?topic=27768.0

**Comment by UnlimitedHugs** [comment]
Some of these have been added in the [2.0.0 update](https://github.com/UnlimitedHugs/RimworldRemoteTech/releases/tag/v2.0.0).
