### ISSUE TITLE
Error in Dev Log when Detonate Bombs

### ISSUE THREAD

**Issue by dat-ho** [UnlimitedHugs/RimworldRemoteExplosives#7]
Tried to destroy already-destroyed thing Plant_TreeOak31925
Verse.Log:Error(String, Boolean)
Verse.Thing:Destroy(DestroyMode)
Verse.ThingWithComps:Destroy(DestroyMode)
RimWorld.Plant:PlantCollected()
RemoteTech.CompMiningExplosive:TryAffectThing(Thing, Thing, Single&)
RemoteTech.CompMiningExplosive:Detonate()
RemoteTech.CompCustomExplosive:CompTick()
Verse.ThingWithComps:Tick()
RemoteTech.Building_RemoteExplosive:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()

**Comment by dat-ho** [comment]
HugLib log: https://gist.github.com/HugsLibRecordKeeper/0ee66fb3f8c423dfbdbf1b5ce06664a4

**Comment by UnlimitedHugs** [comment]
Should be fixed in latest version (2.2.0)
